# https://developer.mozilla.org/ja/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types

## application
string APPLICATION_JSON='application/json'
string APPLICATION_MSWORD='application/msword'
string APPLICATION_MSWORD_OPEN_XML='application/vnd.openxmlformats-officedocument.wordprocessingml.document'
string APPLICATION_OCTET_STREAM ='application/octet-stream'
string APPLICATION_VND_AMAZON_EBOOK='application/vnd.amazon.ebook'
string APPLICATION_X_ABIWORD='application/x-abiword'
string APPLICATION_X_BZIP2='application/x-bzip2'
string APPLICATION_X_BZIP='application/x-bzip'
string APPLICATION_X_CSH='application/x-csh'
string APPLICATION_X_FREEARC='application/x-freearc'
string APPLICATION_X_WWW_FORM_URLENCODED='application/x-www-form-urlencoded'

# application/epub+zip
# application/gzip
# application/java-archive
# application/ld+json
# application/ogg
# application/pdf
# application/rtf
# application/vnd.apple.installer+xml
# application/vnd.mozilla.xul+xml
# application/vnd.ms-excel
# application/vnd.ms-fontobject
# application/vnd.ms-powerpoint
# application/vnd.oasis.opendocument.presentation
# application/vnd.oasis.opendocument.spreadsheet
# application/vnd.oasis.opendocument.text
# application/vnd.openxmlformats-officedocument.presentationml.presentation
# application/vnd.rar
# application/vnd.visio
# application/x-7z-compressed
# application/x-httpd-php
# application/x-sh
# application/x-shockwave-flash
# application/x-tar
# application/xhtml+xml
# application/xml
# application/zip

## audio
string AUDIO_AAC='audio/aac'
# audio/3gpp
# audio/3gpp2
# audio/midi
# audio/mpeg
# audio/ogg
# audio/opus
# audio/wav
# audio/webm
# audio/x-midi

## font
# font/otf
# font/ttf
# font/woff
# font/woff2

## image
string IMAGE_BMP='image/bmp'
string IMAGE_JPEG='image/jpeg'
string IMAGE_PNG='image/png'
# image/gif
# image/svg+xml
# image/tiff
# image/vnd.microsoft.icon
# image/webp

string MULTIPART_FORM_DATA='multipart/form-data'

# pplication/vnd.openxmlformats-officedocument.spreadsheetml.sheet

## text
string TEXT_CSS='text/css'
string TEXT_CSV='text/csv'
string TEXT_HTML='text/html'
string TEXT_JAVASCRIPT='text/javascript'
string TEXT_PLAIN='text/plain'
string TEXT_XML='text/xml'

# text/calendar

## video
string VIDEO_X_MSVIDEO='video/x-msvideo'

# video/3gpp
# video/3gpp2
# video/mp2t
# video/mpeg
# video/ogg
# video/webm


